---
services:
  nginx:
    image: 127.0.0.1:5000/what-to-eat-static
    ports:
      - 80:80
    volumes:
      - type: bind
        source: /var/www
        target: /var/www/html
  nodejs:
    image: 127.0.0.1:5000/what-to-eat-api
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - type: bind
        source: ./nodejs/
        target: /usr/local/share/lunch-api
    entrypoint:
      - 'pm2-runtime'
      - '--watch'
      - 'index.js'
  smtp:
    image: tecnativa/smtp-sink
    ports:
      - 25:25
    container_name: what-to-eat_smtp
    networks:
      - what-to-eat
    logging:
      driver: "syslog"
      options:
        syslog-facility: local0
        tag: "smtp"
