version: '3.5'

services:
  nginx:
    volumes:
      - type: bind
        source: ./nginx/html/
        target: /var/www/html
  nodejs:
    volumes:
      - type: bind
        source: ./nodejs/
        target: /usr/local/share/lunch-api
    entrypoint:
      - 'pm2-runtime'
      - '--watch'
      - 'index.js'
