---
services:
  nginx:
    image: 127.0.0.1:5000/what-to-eat-static
    volumes:
      - type: bind
        source: /var/www
        target: /var/www/html
  nodejs:
    image: 127.0.0.1:5000/what-to-eat-api
    volumes:
      - type: bind
        source: ./nodejs/
        target: /usr/local/share/lunch-api
    entrypoint:
      - 'pm2-runtime'
      - '--watch'
      - 'index.js'
  smtp:
    image: tecnativa/smtp-sink
    networks:
      - what-to-eat
    logging:
      driver: "syslog"
      options:
        syslog-facility: local0
        tag: "smtp"
