#!/bin/sh

if [ -L "$0" ]; then
	F=$(readlink "$0")
else
	F="$0"
fi
P=$(realpath --relative-to="$PWD" "$(dirname "$F")/../etc")
docker run  -e LANG=C.UTF-8 -i --rm --network=lunch mariadb mysqldump -u root -p"$(cat "$P"/db_root_pw)" -h mariadb lunch > /var/backups/lunch_dump.sql

# restore with
# docker run -e LANG=C.UTF-8 -i --rm --network=lunch mariadb mysql -u root -p"$(cat etc/db_root_pw)" -h mariadb lunch < /var/backups/lunch_dump.sql
