extends: eslint:recommended
parserOptions:
  ecmaVersion: 6
  sourceType: script
  ecmaFeatures:
    jsx: false
    experimentalObjectRestSpread: false
env:
  browser: true
globals:
  Vue: readonly
  SwaggerClient: readonly
  VueMarkdown: readonly
rules:
  indent:
  - error
  - tab
  - SwitchCase: 1
  no-unused-vars:
  - error
  - args: none
