extends: eslint:recommended
parserOptions:
  ecmaVersion: 8
  sourceType: script
  ecmaFeatures:
    jsx: false
    experimentalObjectRestSpread: false
env:
  node: true
rules:
  indent:
  - error
  - tab
  global-require:
  - error
  handle-callback-err:
  - error
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  no-console: off
  no-unused-vars:
  - error
  - args: none
globals:
  Promise: false
